# Generated by Django 3.1.7 on 2021-03-12 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.CharField(choices=[('R', 'Red'), ('B', 'Blue')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=9)),
                ('image_set', models.CharField(choices=[('O', 'OG Codenames'), ('U', 'Uptown'), ('M', 'Miller')], max_length=1)),
                ('cards_used', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('color', models.CharField(choices=[('R', 'Red'), ('B', 'Blue')], max_length=1)),
                ('is_spymaster', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.session')),
            ],
        ),
        migrations.CreateModel(
            name='GameCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('assigned_color', models.CharField(choices=[('R', 'Red'), ('B', 'Blue'), ('Y', 'Bystander'), ('A', 'Assassin')], max_length=1)),
                ('image_name', models.CharField(max_length=40)),
                ('is_revealed', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_cards', to='game.game')),
            ],
        ),
    ]
