# Generated by Django 3.1.7 on 2021-03-12 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210311_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='game.session'),
        ),
        migrations.AlterField(
            model_name='player',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='game.session'),
        ),
    ]
