# Generated by Django 3.1.7 on 2021-03-12 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210311_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='game.session'),
        ),
    ]
